---
abstract: "An extended interface to JIRA's SOAP API."
author:
  - 'Gustavo Chaves <gnustavo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120351'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JIRA-Client
no_index:
  directory:
    - t
    - inc
requires:
  IO::Socket: 0
  SOAP::Lite: 0
  Test::More: 0
version: 0.33
