---
abstract: "An extended interface to JIRA's SOAP API."
author:
  - 'Gustavo L. de M. Chaves <gnustavo@cpan.org>'
build_requires:
  English: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300014, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JIRA-Client
requires:
  Carp: 0
  Data::Util: 0
  File::Basename: 0
  MIME::Base64: 0
  SOAP::Lite: 0
  URI: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/gnustavo/JIRA-Client/issues
  homepage: http://search.cpan.org/dist/JIRA-Client/
  repository: git://github.com/gnustavo/JIRA-Client.git
version: 0.38
