--- #YAML:1.0
name:                JIRA-Client
version:             0.03
abstract:            An extended interface to JIRA's SOAP API.
license:             ~
author:              
    - Gustavo Chaves <gnustavo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    IO::Socket:                    0
    SOAP::Lite:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
